name       : neovim
version    : 0.3.5
release    : 13
source     :
    - https://github.com/neovim/neovim/archive/v0.3.5.tar.gz : b8b30043963133214f78901cb6361189c8f94e9f5f1b2493a7cedb4c323236d6
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - jemalloc
    - xclip
setup      : |
    mkdir build
    %cmake -B build -DENABLE_JEMALLOC=ON .
build      : |
    %make -C build
install    : |
    %make_install -C build
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
