name       : neovim
version    : 0.7.0
release    : 27
source     :
    - https://github.com/neovim/neovim/archive/refs/tags/v0.7.0.tar.gz : 792a9c55d5d5f4a5148d475847267df309d65fb20f05523f21c1319ea8a6c7df
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(libluv)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(tree-sitter)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    %cmake_ninja -DUSE_BUNDLED=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
