name       : neovim
version    : 0.9.0
release    : 34
source     :
    - https://github.com/neovim/neovim/archive/refs/tags/v0.9.0.tar.gz : 39d79107c54d2f3babcad2cd157c399241c04f6e75e98c18e8afaf2bb5e82937
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(libluv)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack-c)
    - pkgconfig(termkey)
    - pkgconfig(tree-sitter)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    %cmake_ninja -DUSE_BUNDLED=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim

    # Set EDITOR and VISUAL defaults should nano be removed.

    install -Dm00644 $pkgfiles/80-neovim-is-default-EDITOR-and-VISUAL.sh $installdir/usr/share/defaults/etc/profile.d/80-neovim-is-default-EDITOR-and-VISUAL.sh
    install -Dm00644 $pkgfiles/80-neovim-is-default-EDITOR-and-VISUAL.fish $installdir/usr/share/defaults/etc/profile.d/80-neovim-is-default-EDITOR-and-VISUAL.fish
