name       : neovim
version    : 0.5.1
release    : 23
source     :
    - https://github.com/neovim/neovim/archive/refs/tags/v0.5.1.tar.gz : aa449795e5cc69bdd2eeed7095f20b9c086c6ecfcde0ab62ab97a9d04243ec84
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(libluv)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(tree-sitter)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    %cmake_ninja -DUSE_BUNDLED=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
