name       : neovim
version    : 0.1.7
release    : 4
source     :
    - https://github.com/neovim/neovim/archive/v0.1.7.tar.gz : d8f885d019b1ad608f36ae23b8f1b15b7e33585e16f7514666ab6c9809bb4b7e
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(libuv)
    - pkgconfig(lua-5.1)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    mkdir build && cd build
    %cmake -DENABLE_JEMALLOC=ON ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
