name       : neovim
version    : 0.3.1
release    : 9
source     :
    - https://github.com/neovim/neovim/archive/v0.3.1.tar.gz : bc5e392d4c076407906ccecbc283e1a44b7832c2f486cad81aa04cc29973ad22
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(libuv)
    - pkgconfig(lua-5.1)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    mkdir build && cd build
    %cmake -DENABLE_JEMALLOC=ON ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
