name       : neovim
version    : 0.3.8
release    : 15
source     :
    - https://github.com/neovim/neovim/archive/v0.3.8.tar.gz : 953e134568d824dad7cbf32ee3114951732f9a750c462e430e6b593f418af76c
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - jemalloc
    - xclip
setup      : |
    mkdir build
    %cmake -B build -DENABLE_JEMALLOC=ON .
build      : |
    %make -C build
install    : |
    %make_install -C build
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
