name       : neovim
version    : 0.8.0
release    : 29
source     :
    - https://github.com/neovim/neovim/archive/refs/tags/v0.8.0.tar.gz : 505e3dfb71e2f73495c737c034a416911c260c0ba9fd2092c6be296655be4d18
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(libluv)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(tree-sitter)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    %cmake_ninja -DUSE_BUNDLED=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
