name       : neovim
version    : 0.4.4
release    : 21
source     :
    - https://github.com/neovim/neovim/archive/v0.4.4.tar.gz : 2f76aac59363677f37592e853ab2c06151cca8830d4b3fe4675b4a52d41fc42c
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(libluv)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(msgpack)
    - pkgconfig(termkey)
    - pkgconfig(unibilium)
    - pkgconfig(vterm)
    - gperf
    - libmpack
    - libpth-devel
    - lpeg
rundeps    :
    - xclip
setup      : |
    mkdir build
    %cmake -B build .
build      : |
    %make -C build
install    : |
    %make_install -C build
    ln -s /usr/bin/nvim $installdir/usr/bin/neovim
